services:
  - type: web
    name: whatsapp-mango
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn commerce.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: commerce.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
