databases:
  - name: commerce-db
    plan: free
    databaseName: commerce
    user: commerce

services:
  - type: web
    name: commerce-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn commerce.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: commerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
